### ISSUE TITLE
Issues about far.AdamOptimizer() with ReverseHG

### ISSUE THREAD

**Issue by hy5468** [lucfra/FAR-HO#13]
We work on a sparse logistic regression task on data set 20newsgroups and want to find the best regularization lambda. When we tried to use far.AdamOptimizer() for the inner optimizer and ReverseHG() for hyper optimizer, lambda goes to NAN.  We found that:
1. The hypergradient is an uninitialized value in this situation.
2. The same setting work perfect on ForwardHG() with far.AdamOptimizer().
3. A small learning rate for far.AdamOptimizer() will work, but it is not efficient.
4. A dense version fails too, the reason may be the large feature dimensions?

Best regards,
Xiang Geng

**Comment by lucfra** [comment]
Dear hy5468,

thank you for posting this issue. We have never tested the package with sparse Variables/operations; so it is entirely possible that it does not work as expected. ReverseHG and ForwardHG do slightly different operations, so it is also possible that one works while the other doesn't, but I would not expect this.. 

A quick advice is to set constraint on lambda so that it remains positive throughout the optimization procedure, you can use the `constraint` keyword in `far.get_hyperparameters` , specifically use 

```
contstraint=lambda _v: tf.maximum(0., _v)
```

are you just optimizing a scalar regularization coefficient? If this is the case using ForwardHG is perfectly fine (should also be faster than ReverseHG)!

Answering your questions:
1: not sure I understand.. could you specify?
4. Does it give you out of memory? 

Best, 
Luca
